### PR TITLE
updated to latest swift (3)

### PR DESCRIPTION
**Pull request by MarvinNazari**
No need to merge now, there is one issue on `NSExtensionContextApplicationCallerTests`, i commented out for now

### CODE REVIEW

**Comment by Mazyod** [comment]
Amazing work, thanks! I'll also hopefully spend time before Swift 3 comes out to study the changes to make sure everything is in the right place. This will be a burden to current users, since it's backward incompatible, but I agree that it should be necessary for the long run.

**Comment by Mazyod** [comment]
The demand for Swift 3 support has increased, so it probably makes sense to merge this with the `swift-3` branch on this repo. Do you think you're still able to make it? We're not in a rush yet, btw :)

**Comment by MarvinNazari** [comment]
@Mazyod i haven't checked this with the new beta yet, gonna do it later tonight 👍

**Comment by MarvinNazari** [comment]
@Mazyod just checked with the latest beta and everything works :)

**Comment by Mazyod** [comment]
Much obliged, Sir!

**Comment by Dreamersoul** [comment]
So swift 3 works on `appz:master`? If so should we update the badge in the readme file?

**Comment by MarvinNazari** [comment]
@Dreamersoul no, it's `swift-3`

**Pull request merged**
