### PR TITLE
added the new snapchat "add user" uri

### PR DESCRIPTION
**Pull request by Dreamersoul**

### CODE REVIEW

**Comment by Mazyod** [comment]
I am afraid this is out of sync :pray: Sorry for taking so long to merge those PRs, but will merge this as soon as the conflict is resolved

**Comment by Dreamersoul** [comment]
No worries, I'll get on it as soon as I can

**Comment by Mazyod** [comment]
btw, I don't think Snapchat has a web fallback, so perhaps it's better to use an empty `Path()` for the web part

**Comment by Dreamersoul** [comment]
okay ill fix this now just saw it.

**Pull request closed without merging**
