### PR TITLE
Added Photos, Notes, and TestFlight

### PR DESCRIPTION
**Pull request by Maryom**
Salam :)

@Mazyod Could you please check Photos, Notes, and TestFlight links in readme file and tell me if there are ok or not? Also, I want to make sure it's ok to leave TestFlight fallbackURL empty? because I didn't find home page for it.

### CODE REVIEW

**Comment by Mazyod** [comment]
Thanks, these look perfect :sparkles: I want to add links to the appstore at some point, so if the app doesn't exist, we can open the appstore for the user to download it, but I need to prepare the code design first. We can leave that for v2.0

**Comment by Maryom** [comment]
@Mazyod great idea I like it :+1: I need to take your opinion, I found this awesome link:
https://gist.github.com/phynet/471089a51b8f940f0fb4

I tried them they work just with the following:

```
   UIApplication.sharedApplication().openURL(NSURL(string:"prefs:root=General&path=Keyboard")!)
```

which means that we have to remove // after prefs

I'm thinking to remove it as follow:

```
    var text = String(urlComponents?.URL) as NSString
    text = text.stringByReplacingCharactersInRange(NSMakeRange(15,2), withString:"")
```

but I think it's a bad approach, do you agree with me?

I think it will be great to add them to Appz so I have to come up with a solution to add them.

**Comment by Mazyod** [comment]
@Maryom Thanks, indeed it looks like a useful resource. We just need to make sure Apple allows this and it won't cause apps to be rejected in review.

If it's ok with Apple, there should be a better way to support this type of URL. Adding a new option other than path and query parameters could be the best way. Then, we can make it optional by adding it to a protocol extension.

**Comment by Maryom** [comment]
@Mazyod Yes I agree with you. Who will make sure Apple allows this and it won't cause apps to be rejected in review? While I'm searching I found that Apple will reject the app it it include them! But I don't remember if it's new or old news.

**Comment by Maryom** [comment]
@Mazyod This what I found:
I just got a "rejected" from iTunes Connect this morning, for "prefs:root" is a private API ( there are apps using prefs:root on App Store

http://stackoverflow.com/questions/8246070/ios-launching-settings-restrictions-url-scheme#comment56751438_33896318

So it's better to not implement it, do you agree?

**Pull request merged**
