### PR TITLE
New apps

### PR DESCRIPTION
**Pull request by Maryom**
Added Instapaper, MobileMouse, Simplenote, StitcherRadio, Wikipanion, and Yammer. More apps will be added ASAP :3

### CODE REVIEW

**Comment by Mazyod** [comment]
We need to add a shield for the number of apps, this is great! Thanks,

image

**Comment by Maryom** [comment]
@Mazyod Your welcome :) Do you prefer to add numbers like this?
1 | [eBay][eBay-link] | Open

**Comment by Mazyod** [comment]
It is better to just have a number in the top near "Swift" "pod" .. etc, these are called "shields".

**Comment by Maryom** [comment]
@Mazyod I'm really sorry but I didn't understand. Do you mean like this? 

  2       //  1 CNN.swift  
  3   //  Pods  
  4   //  
  5   //  Created by Mariam AlJamea on 1/15/16.  
  6   //  Copyright © 2015 kitz. All rights reserved.  
  7   //

**Comment by Mazyod** [comment]
screen shot 2016-01-17 at 8 05 06 am

**Comment by Maryom** [comment]
@Mazyod The first time I saw these I love them and I said wow how they added them! they are really awesome I like their color and I like many things in these shields numbers. Could you please guide me how can I add App numbers to them?

**Comment by Maryom** [comment]
@Mazyod I got it :) like this?
Version

**Comment by Maryom** [comment]
Apps number

**Comment by Maryom** [comment]
@Mazyod I will add shield in the next PR with more apps.

**Comment by Dreamersoul** [comment]
badge
we can do this, this is the link
https://img.shields.io/badge/Apps-100-blue.svg
the 100 in the middle is the number of apps, we can update it whenever we want to in the readme file

**Comment by Maryom** [comment]
Ok thanks.

**Pull request merged**
