### PR TITLE
New apps

### PR DESCRIPTION
**Pull request by Maryom**

### CODE REVIEW

**Comment by Mazyod** [comment]
@Maryom I think this PR is broken. There is a duplicate project file or something like that, can you please check?

**Comment by Mazyod** [comment]
maybe not, it's just too many apps added to the appz family :family:

**Comment by Maryom** [comment]
@Mazyod Still there is a problem in 👇🏼?
 I think this PR is broken. There is a duplicate project file or something like that, can you please check?

**Comment by Mazyod** [comment]
it's all good :sparkles:

**Comment by Maryom** [comment]
@Mazyod Ok good 😊 Can I take your opinion in URL fallback?

**Comment by Mazyod** [comment]
yeah

**Comment by Maryom** [comment]
@Mazyod I think there is no need for fallbackURL in all swift class, and no need for web: Path(). Do you agree with me? Can I delete them all?

**Comment by Mazyod** [comment]
Why? This is one of the most important features of Appz

**Comment by Maryom** [comment]
@Mazyod because every iPhone has App Store app on it, so if the user didn't install any app Appz will open App Store directly no need to go to safari, right?

**Comment by Mazyod** [comment]
No, maybe the app has a website, like twitter, and the developer doesn't want to bother the user with installing the app, and just show the twitter webpage

**Comment by Maryom** [comment]
@Mazyod Ok :)

**Pull request merged**
