### PR TITLE
Added new apps :3

### PR DESCRIPTION
**Pull request by Maryom**
Salam :) 

New apps are: Netflix, Spark, Weibo, Name Shark, Ali Express, Flipps TV, Friendly Social, and Heapo.

### CODE REVIEW

**Comment by Mazyod** [comment]
This is looking great, but I don't see the AppStore Rate action implemented?

**Comment by Maryom** [comment]
@Mazyod I forgot to add it 😅 I will add it إن شاء الله

**Comment by Mazyod** [comment]
Did you test the rate action with at least two different apps? It looks to me like there are some hard coded parameters

**Comment by Maryom** [comment]
@Mazyod Yup I tested it with two apps.

**Comment by Mazyod** [comment]
Interestingly, "Purple Software" turns out to be a code name used within apple ... Sounds pretty lame, but oh well. Microsoft does a better job on that front, IMHO :)

**Comment by Maryom** [comment]
@Mazyod Great :) Thanks for sharing this nice info.

**Pull request merged**
