### PR TITLE
Added Audible, DayOne, Documents, eBay, FindFriends, Flickr, Paypal, …

### PR DESCRIPTION
**Pull request by Maryom**
…and WhatsApp

Salam :) Hmmm I don't know if git commit push all the commit or cut it because it appears with ... Anyways, I added  Audible, DayOne, Documents, eBay, FindFriends, Flickr, Paypal and WhatsApp and I'm so excited to add more apps ASAP :) and I'm so happy about this tweet:
CremeDeLaPods: [Appz by @SwiftKitz] Deeplinking to external applications made easy! https://t.co/uEOPCNjx6p

And finally I need to take your opinion in the following:
I named eBay swift file with e as small letter, it's ok? or do you prefer to name it Ebay.swift because it's a common way in programming to start with capital letter.

Thanks ..

### CODE REVIEW

**Comment by Mazyod** [comment]
Thanks for adding yet another batch of apps! The tweet got us a couple stars, which was nice :)

About eBay, I don't mind either way, but since you used `Itranslate` before in this project, it will be inconsistent to use `eBay`. One of them must be renamed to follow the other.

**Comment by Dreamersoul** [comment]
wow this is amazing :+1:

**Comment by Maryom** [comment]
Your welcome :)  إن شاء الله tonight I will add more apps and I will rename Ebay files.

**Comment by Maryom** [comment]
Salam :) I added Added GooglePlus, GoogleEarth, GoogleMail, Ibooks, Quora, and INRIXTraffic and renamed eBay files and I rearranged apps in README file in alphabet order. My plan is to add apps as much as I can so that we get many stars 🌟 ربي يرزقنا 
So I will add إن شاء الله more apps with just open action then I will try to add more actions to these apps.

**Comment by Maryom** [comment]
Oops I forgot to tell you that I need to take your opinion, Do you prefer to keep fallbackURL for iBooks empty or not? I put http://www.apple.com/ibooks/ but I think it's better to keep it empty.

**Comment by Mazyod** [comment]
@Maryom Yeah, it's probably a good idea to leave it empty. Trying to open the app should return `false` in that case, allowing the developer to use `Applications.AppStore` to allow the user to download iBooks, or do whatever makes sense in that context. So, we will leave it as a responsibility of the developer.

**Comment by Maryom** [comment]
@Mazyod Ok done I fix them in both files: Ibooks.swift and IbooksTests.swift.

**Comment by Mazyod** [comment]
@Maryom Super, much appreciated as always :sparkles: !

**Comment by Maryom** [comment]
@Mazyod Thanks 😊

**Pull request merged**
