### PR TITLE
Added openFromID and changed 'fallbackURL' Telegram.swift

### PR DESCRIPTION
**Pull request by ParhamHatan**
Updated Telegram.swift
With openFromID you can open channels and user page ( group not tested )
Test files not changed

### CODE REVIEW

**Comment by Mazyod** [comment]
Thanks, can you update the tests?

**Comment by ParhamHatan** [comment]
can you test both files yourself please ?

**Comment by Mazyod** [comment]
Tested both, works great. Thanks for your contribution! Great channel, as well :D

**Comment by ParhamHatan** [comment]
thanks for your great source

**Comment by ParhamHatan** [comment]
Can you update telegram in readme file too ?

**Pull request merged**
