### PR TITLE
Removed Word, Excel, PowerPoint, OneNote, and MSPayload

### PR DESCRIPTION
**Pull request by Maryom**
Done :)

### CODE REVIEW

**Comment by Mazyod** [comment]
Can you please fix the tests?

**Comment by Maryom** [comment]
I removed them. What is the problem?

**Comment by Maryom** [comment]
I think I found the solution. git rm was the problem.

**Comment by Maryom** [comment]
I'm getting the following error:
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Pull request closed without merging**
