### PR TITLE
Removed MS apps

### PR DESCRIPTION
**Pull request by Maryom**
Done?

### CODE REVIEW

**Comment by Mazyod** [comment]
You can see the status very clearly and if there are errors on the travis-ci website. For now, it's building:
https://travis-ci.org/SwiftKitz/Appz

**Comment by Maryom** [comment]
OK

**Comment by Maryom** [comment]
Done 😭 Sorry for bothering you.

**Comment by Mazyod** [comment]
:8ball: score!

**Comment by Maryom** [comment]
😊

**Comment by Mazyod** [comment]
It is probably just too late in Kuwait, make sure you take a break as well!

**Comment by Maryom** [comment]
Ok thanks 😊

**Pull request merged**
