### PR TITLE
Added Facebook and tested it

### PR DESCRIPTION
**Pull request by Maryom**

### CODE REVIEW

**Comment by Mazyod** [comment]
Great, thanks! Can you please submit a PR adding Facebook to the readme as well?

**Comment by Mazyod** [comment]
Nvm the facebook readme, it was merged in #16 .. Thanks again!

**Comment by Maryom** [comment]
Your welcome :) New PR is on his way 🚀 But does NVM stand for non volatile memory?!

**Comment by Mazyod** [comment]
lol, no .. [Urban dictionary is your friend in these situations](http://www.urbandictionary.com/define.php?term=nvm&utm_source=search-action).

**Comment by Maryom** [comment]
😁😅

**Pull request merged**
