### PR TITLE
Added DailyMotion, Trello, Twitterrific, and Waze

### PR DESCRIPTION
**Pull request by Maryom**

### CODE REVIEW

**Comment by Mazyod** [comment]
Looks great, thanks for another great package of apps :package: !

**Comment by Maryom** [comment]
Your welcome. I want to check: Twitterrific doesn't have web app like Twitter correct? I leave it web path empty, it's ok?

**Comment by Mazyod** [comment]
Yes, that's correct.

On January 5, 2016 at 8:23:06 AM, Maryom (notifications@github.com) wrote:

Your welcome. I want to check: Twitterrific doesn't have web app like Twitter correct? I leave it web path empty, it's ok?

**Comment by Maryom** [comment]
Ok thanks.

**Pull request merged**
