### PR TITLE
New Apps

### PR DESCRIPTION
**Pull request by Maryom**
Salam,

I added Foursquare, Pocket, RunKeeper, Box, FileApp, LastPass, Ustream, VIPAccess, and supported apps shields.

### CODE REVIEW

**Comment by Mazyod** [comment]
Thanks, that purple badge looks awesome! :space_invader:

**Comment by Maryom** [comment]
@Mazyod Your welcome :) Yup I love purple.

**Comment by Maryom** [comment]
@Mazyod I will be glad to know what is your wish apps number for Appz?

**Comment by Mazyod** [comment]
yeah, that is good question. I think we can concentrate on cleaning up a few things in Kitz, and try to push it to the people on stackoverflow and other websites. Having 115 apps is amazing, and should allow people to get started and submitting their contributions. So, we can hope that more people will contribute small chunks, instead of us doing all the work :)

**Comment by Maryom** [comment]
@Mazyod Well I found around 4000+ URL schemes and it's ok to me to add more apps as possible as I can. But I think it's better to try solving issues do you agree with me?

**Comment by Mazyod** [comment]
yeah, instead of manually adding them all, we may just write a script for that instead. But again, yeah focusing on the issues comes first.

**Comment by Maryom** [comment]
Wow script, it will be awesome. How can we do it?

**Comment by Mazyod** [comment]
I'm not really good at scraping, but that is the name of it. We can explore that further after dealing with the other issues first.

**Comment by Maryom** [comment]
Ok deal.

**Comment by Dreamersoul** [comment]
I could have a shot at writing a script, can you link the schemes and I'll look into it?

**Comment by Maryom** [comment]
This is the link:
http://api.sevastian.net/schemes/search?page=6

Thanks.

**Pull request merged**
