### PR TITLE
Added links for the apps website

### PR DESCRIPTION
**Pull request by Maryom**
Done I added links for the apps website, @Mazyod Could you please check the following links:
AppStore, FindFriends, iBooks, and WhatsApp

And tell me this is what you need? feel free to tell me fix them.

### CODE REVIEW

**Comment by Mazyod** [comment]
Can you please fix the links? They should be added to the end of the readme file.

You can see an example in the readme file, just search for `cocoapods-link`.

**Comment by Maryom** [comment]
Done, Now everything is ok? Feel free to tell me fix something or to assign new task for me :)

**Comment by Mazyod** [comment]
Looks good, thanks for another great contribution :+1:

**Comment by Maryom** [comment]
You are welcome.

**Pull request merged**
