### PR TITLE
A suggestion solution to issue Just the needed app #85

### PR DESCRIPTION
**Pull request by Maryom**
Salaam,

This is just a suggestion it needs some improvement, I just pulled it to check the idea with you. Once you reviewed it we will discuss it إن شاء الله because I like some part of it and I dislike some other parts.

### CODE REVIEW

**Comment by Mazyod** [comment]
So it what ways does this suggestion improve the existing design?

**Comment by Maryom** [comment]
@Mazyod it will improve it by deleting all files that just have open action. Because it's too much to have 155 files and they will increase in the future. Do you agree? instead of using files we will you cases so one file for almost 50+ apps

**Comment by Maryom** [comment]
Still I didn't try with iOS 10 issue because I think it's important to decrease file number. Do you agree?

**Comment by Mazyod** [comment]
Not really, decreasing the number of files by merging code together is not going to solve the problem.

**Comment by Maryom** [comment]
Yes it not related to iOS 10 but it's important to decrease file number, correct?

**Comment by Mazyod** [comment]
It's a very subtle difference, but we should decrease the amount of code, not the number of files. If you have 100 files all containing 10 lines of code, it's the same as having one file with 1000 lines of code .. Except, it's actually better to have more files in most cases like this.

**Comment by Dreamersoul** [comment]
Can't we do something in the build phases to include only specific apps?

**Comment by Maryom** [comment]
Yes this is exactly what I'm trying to say we have to decrease lines of code, and I think by using this way we can decrease it. And to improve it more we can move:
`enum TheNeededApp`

to separate swift file. so we will end with two files:
1. with few lines OpenApp.swift with 52 lines.
2. TheNeededApp file we will know its lines number when you agree I will add all apps and we will see. I think we will end with less lines of code, correct?

**Comment by Maryom** [comment]
Also, we can use it as follow:

```
let app = UIApplication.shared
        app.open(Applications.OpenApp(theApp:TheNeededApp(rawValue: "sketch"
        )!), action: .open)
```

**Comment by Maryom** [comment]
Also, to decrease lines we can combine the computed property.

**Comment by Mazyod** [comment]
@Dreamersoul That could be a possible solution, although I am not quite sure how that will work. Should the build phase be a copy files script? Should it be a shell script that modifies the project? In general, adding a build phase is a powerful tool, but should be used with care.

**Comment by Maryom** [comment]
As follow:

```
var theData: (String, String, String) {
        switch self {
        case .NYTimes:
            return ("nytimes:", "https://ride.jp/", "284862083")
        case .skitch:
            return ("skitch:", "https://evernote.com/skitch/", "1088140538")
        }
    }
```

**Comment by Mazyod** [comment]
@Maryom It really doesn't reduce the lines of code significantly, and only makes it harder to use the library. Adding all apps in a single file is definitely not the solution.

**Comment by Mazyod** [comment]
@Maryom We **must** consider readability and usage of the library. When a user sees a 3 tuple string like this `(String, String, String)`, they don't know what this is.

**Comment by Maryom** [comment]
Not all apps just apps with open action. Other apps with still have their own file.

**Comment by Mazyod** [comment]
@Maryom That will break the consistency of the library, which is not really a good thing

**Comment by Maryom** [comment]
Ok as you like.

**Comment by Maryom** [comment]
There is a way to specify which files to install with pod install ? I searched but I didn't find a way.

**Comment by Mazyod** [comment]
@Maryom Yes there is, but it's fixed for the most part, unless we create a pod spec for every single app we add, which might be the only way.

**Comment by Maryom** [comment]
Yes I read about pod spec but I didn't understand it well. So let's do it because we need a solution.

**Comment by Mazyod** [comment]
well, I'm not yet sure about this solution because it doesn't solve the problem for people who might be using Carthage, or Swift Package Manager in the future .. So, fixing Cocoapods isn't the best solution, I think we should allow more time for thinking of a better way.

**Comment by Dreamersoul** [comment]
We can create a shell file that gets invocted on build that reads a Json file to include specific apps

**Comment by Mazyod** [comment]
@Dreamersoul I just realized that the build phase approach is not portable across package managers. I am in favor of the pod spec approach, but we need to know if there is a way to simplify it within our release process...

So, for example, instead of us writing all the Swift files by hand, we create a configuration file (Plist, JSON, ... etc) that contains all the information about deeplinking (scheme, actions, ... etc). When we make a new Appz release, a script is triggered that generates all the needed Swift files, pod specs, and so on ... That will be a very simple approach, since the user of the library won't have to do anything except specify in the podfile:

``` ruby
pod "Appz/Whatsapp"
pod "Appz/Telegram"
...
```

But, I would still like it to be solved for Carthage and SPM, if possible, and make sure this is the best approach.

**Comment by Mazyod** [comment]
Of course, @Maryom mentioned writing the script and the Cocoapod specs ideas, so I still think her approach is the right way .. We just need to take it all the way to the end.

**Comment by Maryom** [comment]
@Mazyod I agreed with pod "Appz/Whatsapp" approach. So could you please give us idea how can we start?  to be honest a lot of things are new to me but I want to learn.

And can you give us schedule and deadlines and what should each member do so we manage to do it well.

**Comment by Mazyod** [comment]
@Maryom I really can't, unfortunately. I won't be contributing features to Kitz for at least 3 months, since I have so much work to do.. All I can do for now is discuss new ideas and help drive the conversation, that's all.

**Comment by Maryom** [comment]
@Mazyod Salaam,
I think the solution is Subspecs as mentioned here:
https://guides.cocoapods.org/making/specs-and-specs-repo.html

Do you agree?

**Pull request closed without merging**
