### PR TITLE
Added demo gif to readme file

### PR DESCRIPTION
**Pull request by Maryom**

### CODE REVIEW

**Comment by Mazyod** [comment]
Thanks! Let's try to make sure the image resolution and size make sense .. It is a bit too big now, with a relatively large size.

**Comment by Maryom** [comment]
@Mazyod Ok I'm recording the updated one now.

**Comment by Maryom** [comment]
@Mazyod Ok? if still not ok feel free to tell me :)

**Comment by Maryom** [comment]
@Mazyod Well I think it's better if I make it smaller, I will make it إن شاء الله within 48 hours in maximum. Sorry but I have something suddenly happened.

**Comment by Dreamersoul** [comment]
can we use the app in the gif as a demo app with source in the sandbox repo?

**Comment by Maryom** [comment]
@Mazyod Salam, hmmmm do you think it's ok now? the video in my browser works very fast, I don't know if it works to all as it works to me! Secondly, If you want to make it more smaller feel free to tell me :)

**Comment by Maryom** [comment]
@Mazyod This one is better, do you agree?  If you want to edit it more feel free to tell me :)
P.S. sorry I wrote lol as a commit because I don't know what to write, but now I saw that Lol and lool appear to everyone 😅🙊

**Comment by Mazyod** [comment]
@Maryom lol, gifs are always fun! This size is much better, if you can please center it, I can merge

**Comment by Mazyod** [comment]
@Dreamersoul I am against adding a demo within this repository, since it will be harder to maintain and write proper tests for. We should use [SwiftKitz/sandbox](https://github.com/SwiftKitz/sandbox)

**Comment by Maryom** [comment]
@Mazyod Like this? please if you want me to edit it more feel free because PR make me happy 😊 I would like to add frame to it or some polish ✨

**Comment by Maryom** [comment]
I compressed it from 27.6 MB to 2.1MB :)

**Comment by Mazyod** [comment]
excellent, the quality is also superb! Thanks again!

**Comment by Maryom** [comment]
@Mazyod Most welcome :)

**Pull request merged**
