### PR TITLE
Added new apps :3

### PR DESCRIPTION
**Pull request by Maryom**
Salam :)

I added AllCast, Buzzfeed, Chromecast, Cnet, Fitbit, iShows, iTunesU, Marvis, Meerkat, MyFitnessPal, OnePassword, Periscope, Radium, Super Stickman Golf 2, Ted, and Whyd.

@Mazyod Just one small note:
Marvis fallbackURL shows this 👇🏼
marvis

But when I tapped continue or cancel I forgot what I tapped. Anyways, it works fine. So should I keep it or it's better to leave the fallbackURL empty?

إن شاء الله More Apps will be added ASAP :3

### CODE REVIEW

**Comment by Mazyod** [comment]
Thanks, about Marvis, you can simply change `https` to `http`. That should fix the warning.

**Comment by Maryom** [comment]
@Mazyod Your welcome, Ok done I changed https to http and I add five more apps :3

**Comment by Mazyod** [comment]
@Maryom You also need to update the test :x: :grin:

**Comment by Maryom** [comment]
@Mazyod I updated them 😁 Ok I will delete my frok and PR new one, do you think it will solve the  :x:

**Comment by Mazyod** [comment]
@Maryom just update the code and push a new commit, that's all

**Comment by Maryom** [comment]
@Mazyod Ok I understood you Marvis test yup I didn't update it.

**Comment by Mazyod** [comment]
Thanks, this is looking great :star2:

**Comment by Maryom** [comment]
@Mazyod Your welcome 😊 Thanks for all stars you wrote I like them 💯 I don't know where is our conversation about App setting so I will tell you here: this is what I found:
I just got a "rejected" from iTunes Connect this morning, for "prefs:root" is a private API ( there are apps using prefs:root on App Store

http://stackoverflow.com/questions/8246070/ios-launching-settings-restrictions-url-scheme

So do you think no need to implement App Setting?

**Comment by Mazyod** [comment]
@Maryom Thanks, yes this confirms my doubts .. We shouldn't add it unless it's documented by Apple.

**Comment by Maryom** [comment]
@Mazyod Ok deal :)

**Pull request merged**
